#!/usr/bin/env python3


include: "rules/common.smk"


rule parse_bpa_json:
    input:
        json="resources/datasets.jsonl.gz",
    output:
        sample_id_dict="results/sample_id_dict.jsonl.gz",
        bioplatforms_id_dict="results/bioplatforms_id_dict.jsonl.gz",
        equivalent_samples="results/equivalent_samples.jsonl.gz",
    log:
        "logs/parse_bpa_json.log",
    script:
        "scripts/parse_bpa_json.py"


rule dump_bpa:
    params:
        apikey=get_apikey(),
        url=config["bpa_url"],
    output:
        "resources/datasets.jsonl.gz",
    log:
        "logs/dump_bpa.log",
    shell:
        "ckanapi search datasets "
        " -a {params.apikey} "
        "include_private=true "
        "-O {output} "
        "-z "
        "-r {params.url} "
        "&> {log}"
