#!/usr/bin/env python3

import os
from snakemake.logging import logger


def get_apikey():
    apikey = os.getenv("BPI_APIKEY")
    if not apikey:
        logger.warning("Set the BPI_APIKEY environment variable.")
        return None
    return apikey


configfile: "config/config.yaml"


rule dump_bpa:
    params:
        apikey=get_apikey(),
        url=config["bpa_url"],
    output:
        "resources/datasets.jsonl.gz",
    log:
        "logs/dump_bpa.log",
    shell:
        "ckanapi search datasets "
        " -a {params.apikey} "
        "include_private=true "
        "-O {output} "
        "-z "
        "-r {params.url} "
        "&> {log}"
